# Generated by Django 3.0.3 on 2020-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0002_auto_20200408_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
